### ISSUE TITLE
README review

### ISSUE THREAD

**Issue by edhager** [dojo/cli-create-widget#14]
- Remove the WARNING.
- The TOC needs to be updated.
- This is a comment for all @dojo READMEs...  We are not consistent with how we specify the npm install command.  Sometimes we use `npm i` and sometimes `npm install'.  This one uses `npm install` which I think is the better choice.
- I would like to see a bit more info about the custom element descriptor.  Explain what creating a custom element means in regards to the widget.  Why would I want to create one?  Explain how to use the custom element.  Explain how many or how few Dojo 2 components does one need to load in an app to use the custom element.  Maybe compare using a custom element versus the widget.  How do I decide which way to go?  Pros and cons. Stuff like that.

**Comment by edhager** [comment]
Are custom elements a good way to transition into using Dojo 2?

**Comment by mwistrand** [comment]
@edhager Most, if not all, of these concerns have been been addressed in other PRs (e.g., #12). Since the custom element functionality is defined by [`widget-core`](https://github.com/dojo/widget-core), the reference to `widget-core` in the README may be enough for this package. Is there anything in the current README that can still be improved upon?

**Comment by edhager** [comment]
Looks good.
